### ISSUE TITLE
크롬 플러그인 : Stylish

### ISSUE THREAD

**Issue by DrMaemi** [DrMaemi/blog#133]
<details>
<summary>css editor</summary>

```css
@namespace url(http://www.w3.org/1999/xhtml);
/*
 * Basic layout
 */

.zh-select-menu-modal {
    left: 270px;
}

.col-9,
.col-md-9 {
    width: calc(100% - 250px);
}

.col-3,
.col-md-3 {
    width: 250px;
}

.container {
  width: 100% !important;
  padding-right: 30px !important;
  padding-left: 30px !important;
}

/* Responsive containers on some pages */
.container-lg,
.container-xl {
  max-width: 100% !important;
  padding-right: 30px !important;
  padding-left: 30px !important;
}

/* Match the header to container padding */
.Header {
  padding-right: 30px !important;
  padding-left: 30px !important;
}


/*
 * Profile pages
 */

.pinned-repo-item {
  width: calc(50% - 10px) !important;
}
.org-pinned-repos-list .pinned-repo-item {
  width: calc(33.3% - 10px) !important;
}

.u-photo,
.user-status-container {
  max-width: 250px;
}
.u-photo .avatar {
  width: 100% !important;
  height: auto !important;
}


/*
 * Repo-specific stuff
 */

.repository-content {
  width: 100% !important;
}

/* Undo container changes for the Projects tab on repos which have unnecessary nested container-lg's */
.repository-content > .container-lg {
  padding-right: 0 !important;
  padding-left: 0 !important;
}

/* Undo for profile timeline */
.contribution-activity-listing .discussion-timeline {
  width: 100% !important;
}

/* Fix #18 - props: @auscompgeek */
.file-header::after {
  clear: left !important;
}

/* Network graph */
#network {
  max-width: 730px;
}


/*
 * Issues & Dashboard
 */

#dashboard,
.new-issue-form {
  position: relative !important;
}

.new-issue-form .discussion-sidebar {
  position: absolute !important;
  top: 0 !important;
  right: 0 !important;
}

button.discussion-sidebar-toggle {
  width: 100% !important;
}

.timeline-new-comment {
  max-width: none !important;
}

/* Commits: extended message under "..." */
.commit-desc pre {
  max-width: none;
}

/* Alert messages */
#js-flash-container .flash-messages {
  width: 100% !important;
  padding-left: 30px !important;
  padding-right: 30px !important;
}
```
</details>
